sudo: true
merge_mode: replace   # for custom builds
language: cpp
matrix:
#   include:
#     - os: linux
#       dist: bionic
#       name: bionic linux, python3.6
#       compiler:
#         - clang
include:
  - os: osx
    osx_image: xcode10.1
    name: osx
    compiler:
        - clang

before_install:
  - gcc -v
  - g++ -v
  
  - echo $LANG
  - echo $LC_ALL
#  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libboost1.65-all-dev libssl-dev  ; fi
if [ "$TRAVIS_OS_NAME" = "osx"   ]; then brew reinstall openssl                    ; fi
#  - git clone https://github.com/named-data/ndn-cxx.git && cd ndn-cxx
#  - git checkout ndn-cxx-0.7.0
#  - ./waf configure && ./waf && sudo ./waf install && cd ..
#  - git clone https://github.com/named-data/NFD.git && cd NFD
#  - git checkout NFD-0.7.0
#  - ./waf configure --without-libpcap --without-websocket && ./waf && sudo ./waf install && cd ..
#  - wget https://github.com/yufengzh/NAC-ABE/releases/download/v1.0/libopenabe-1.0.0-linux.tar.gz
#  - tar -xf libopenabe-1.0.0-linux.tar.gz && cd libopenabe-1.0.0-linux
git clone https://github.com/zeutro/openabe.git && cd openabe
  - ./deps/install_pkgs.sh
  - . ./env
  - make && make test && sudo -E make install && cd ..

  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ldconfig ; fi
  # - ndnsec-key-gen test
  # - sudo nfd start -c /usr/local/etc/ndn/nfd.conf.sample &
install: 
  - ./waf configure --with-tests
  - ./waf
  - sudo ./waf install
script:
  - ./build/unit-tests