sudo: true
merge_mode: replace   # for custom builds
language: cpp
matrix:
  include:
    - os: linux
      dist: bionic
      name: bionic linux, python3.6

before_install:
  - sudo apt install -y g++ pkg-config python3-minimal libboost-all-dev libssl-dev libsqlite3-dev cmake build-essential bison byacc flex libgmp3-dev
  - git clone https://github.com/named-data/ndn-cxx
  - cd ndn-cxx/
  - git checkout ndn-cxx-0.7.0
  - ./waf configure && ./waf && sudo ./waf install && cd ..
  - wget https://crypto.stanford.edu/pbc/files/pbc-0.5.14.tar.gz
  - tar xzvf ./pbc-0.5.14.tar.gz pbc-0.5.14/
  - cd pbc-0.5.14/
  - ./configure
  - make && make install
  - cd ..
  - wget http://hms.isi.jhu.edu/acsc/cpabe/libbswabe-0.9.tar.gz
  - tar xzvf libbswabe-0.9.tar.gz
  - cd libbswabe-0.9/
  - ./configure
  - make
  - make install
  - cd ..
  - wget https://github.com/yufengzh/NAC-ABE/releases/download/v1.0/libopenabe-1.0.0-linux.tar.gz
  - tar xzvf libopenabe-1.0.0-linux.tar.gz
  - cd libopenabe-1.0.0-linux/
  - . ./env
  - make && make install
  - cd ..
install:
  - ./waf configure --with-tests
  - ./waf
  - sudo ./waf install
script:
  - ./build/unit-tests