name: C/C++ CI

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: preinstall
      run: |
       echo $LANG
       echo $LC_ALL
       sudo apt-get install -y flex libboost1.65-all-dev libsqlite3-dev libssl-dev
    
      # - git clone https://github.com/named-data/ndn-cxx.git && cd ndn-cxx
      # - git checkout ndn-cxx-0.7.0
      # - ./waf configure && ./waf && sudo ./waf install && cd ..
      # - git clone https://github.com/named-data/NFD.git && cd NFD
    
      # manually install relic
       wget --no-check-certificate https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/relic-toolkit/relic-0.3.5.tar.gz
       tar -xf relic-0.3.5.tar.gz && cd relic-0.3.5
       cmake CMakeLists.txt
       make
      # - make test
       sudo make install
       cd ..
    
       wget https://github.com/yufengzh/NAC-ABE/releases/download/v1.0/libopenabe-1.0.0-linux.tar.gz
       tar -xf libopenabe-1.0.0-linux.tar.gz && cd libopenabe-1.0.0-linux
       sudo -E ./deps/install_pkgs.sh
       . ./env
       make && make test && sudo -E make install && cd ..
    
       sudo ldconfig
       ndnsec-key-gen test
           
    - name: install
      run: ./waf configure --with-tests
           ./waf
           sudo ./waf install
 
    - name: test
      run: ./build/unit-tests
